### ISSUE TITLE
`transactions` request return txs that is out of from-to blocks range

### ISSUE THREAD

**Issue by code-brewer** [blockfrost/blockfrost-js#245] opened 2022-11-28 16:27 UTC
I just fiddle with the api to get transactions of given block-range, but it alway return all Txs which is not my expected.

After hours countless retries, still unable to found why it do work.

Here is my account and run log  with `debug` option on.

```bash
GET https://cardano-preview.blockfrost.io/api/v0/addresses/addr_test1vqp8q8r6090emxz07zx5mycznazfknqrxuzcz7h2uk6ss2gqrqjau/transactions?page=1&count=100&order=asc&from=141117&to=141119
[
  {
    tx_hash: 'ee2328023bd1cfca8fc3c03e8bba448a1026c5bc6e1a4e7afb1f7ff7bb43b2af',
    tx_index: 7,
    block_height: 140963,       // this should not return as it not fall into "from=141117&to=141119" range
    block_time: 1669619753
  },
  {
    tx_hash: '087cc806c3869d80b420fa05a8967ae6dd58373a4c554c526542fbb7b9f54fb9',
    tx_index: 4,
    block_height: 141085,     // this should not return as it not fall into "from=141117&to=141119" range
    block_time: 1669622478
  },
  {
    tx_hash: '33f532747084d1392fa8a0154ec5ed3e8015c52c35f9b4a90bb750c3cb137a30',
    tx_index: 8,
    block_height: 142129,    // this should not return as it not fall into "from=141117&to=141119" range
    block_time: 1669643438
  }
]
```

I suspect that maybe I missed something , it is not likely the bug of BlockFrost.

Can anyone point me out? 

Thanks.

**Comment by slowbackspace** [comment] 2022-11-28 17:22
Hi @code-brewer!
What version of the SDK are you using? Could you provide code example?

It seems I cannot reproduce it, code below returns an empty array.

```
import { BlockFrostAPI } from '@blockfrost/blockfrost-js';

async function run() {
  const API = new BlockFrostAPI({
    projectId: 'preview...',
  });

  try {
    const txs = await API.addressesTransactions(
      'addr_test1vqp8q8r6090emxz07zx5mycznazfknqrxuzcz7h2uk6ss2gqrqjau',
      undefined,
      { from: '141117', to: '141119' },
    );
    console.log('txs', txs);
  } catch (err) {
    console.log('error', err);
  }
}

run();

```

**Comment by code-brewer** [comment] 2022-11-28 17:32
@mmahut  Thanks for your reply. I have try your approach and got the same expected result as your.
Maybe the cache caused get me wrong data. Because in my initial experiment,  there are many full range queries on same address before the  "from=141085&to=141119" query. 
I'm doing more test and will feedback later.

**Comment by code-brewer** [comment] 2022-11-28 17:35
@slowbackspace  Appreciates your suggestion. I got some clues and just digging the root out.

**Comment by code-brewer** [comment] 2022-11-28 17:53
Can not reproduce now. It actually puzzled me for two days.
Any way, glad to see my testing move forward.
Thanks.

**Comment by slowbackspace** [comment] 2022-11-29 09:08
@code-brewer That's great! I'll close this issue. if you experience any problem don't hesitate to open another one :)

**Closed by slowbackspace** 2022-11-29 09:08 UTC
